idle tips video url added to default config
mentorpal/mentor-graphql pull request #43
Opened 2021-07-20 20:39 UTC by aaronshiel

2021-07-26 22:07 UTC, beatthat requested changes
looks good, just name changes

2021-07-26 22:07 UTC, beatthat commented on node/src/gql/types/config.ts
> +    idleTipsVideoUrl: { type: GraphQLString },
can go diff ways, but let's follow the name convention in place here so make it `urlVideoIdleTips`

2021-07-29 04:01 UTC, aaronshiel commented
alpha tested on:
(mentor-admin) 4.2.0-alpha.26
(mentor-graphql) 4.2.0-alpha.3

2021-07-29 19:19 UTC, beatthat requested changes
Looks good. There's a note about making the override url different from the default, so let's fix that.

Also, the whole way auth was done with `extensions` in every GQL response is just plain wrong. That's not the responsibility of this PR to fix it, but I do not want every spec in our test suite infected with that `extensions` garbage.

I guess easiest alt would be...

```typescript
expect(response.body?.data?.config).eql(
  {
     urlIdleVideo: 'some/url',
     // ...
   }
)
```

2021-07-29 19:19 UTC, beatthat commented on node/test/graphql/query/config.spec.ts
> +      urlVideoIdleTips: 'https://youtu.be/xSu1BhuFt8A',
this url is the same as the default url, so it's not really testing anything. Change to like 'https://some/custom/url'

2021-07-29 20:36 UTC, beatthat requested changes
small inline

2021-07-29 20:36 UTC, beatthat commented on node/test/graphql/query/config.spec.ts
> +    expect(response.body.data.config).to.eql({
make sure to use optional chaining here...if this test fails with data=null we want it to fail as an expectation mismatch and NOT a null-pointer ref that throws from the test code

2021-07-29 20:44 UTC, beatthat approved these changes
Go ahead and release this, test it locally and then deploy to v2 if it looks good

2021-07-29 20:44 UTC, merged