Import video mentor
mentorpal/mentor-graphql pull request #51
Opened 2021-08-09 20:55 UTC by kycarr

- [x] for all new queries/mutations etc. use id not _id (mongoose provides id)
- [x] for all new queries/mutations etc. use noun-first names (mediaUpload)
- [x] some details about how to calculate needsTransfer and making sure that logic is not duplicated

2021-08-11 20:00 UTC, beatthat requested changes
looks good!

Main asks are:

 - for all new queries/mutations etc. use `id` not `_id` (mongoose provides `id`)
 - for all new queries/mutations etc. use noun-first names (`mediaUpload`)
 - some details about how to calculate `needsTransfer` and making sure that logic is not duplicated

2021-08-12 22:06 UTC, kycarr commented on node/src/gql/mutation/api/update-media.ts
> +      media.find((m) => m.needsTransfer) !== undefined;
needsTransfer is already a boolean, what's the point of casting it as a boolean?

2021-08-12 23:43 UTC, beatthat commented on node/src/gql/mutation/api/update-media.ts
> +      media.find((m) => m.needsTransfer) !== undefined;
ah, meant this. 

```typescript
Boolean(media.find((m) => m?.needsTransfer));
```

...the point is we generally always avoid comparing things explicitly to `undefined`

2021-08-13 01:15 UTC, beatthat requested changes
looks really close, had one more idea for how to consolidate/encapsulate the logic about static urls, see inline

2021-08-13 01:15 UTC, beatthat commented on node/src/models/Mentor.ts
> +import { Answer, mediaNeedsTransfer, Status } from './Answer';
let's move that `mediaNeedsTransfer` function to a `utils/static-urls` module (see above)

2021-08-13 01:15 UTC, beatthat commented on node/src/gql/types/answer.ts
> +        if (media.needsTransfer || media.url.startsWith('http')) {
```typescript
import { toAbsoluteUrl } from 'utils/static-urls'
return toAbsoluteUrl(media.url)
```

2021-08-13 01:15 UTC, beatthat commented on node/src/models/Mentor.ts
> +      m.url = m.needsTransfer
```typescript
import { mediaNeedsTransfer, toRelativeUrl } from 'utils/static-urls'

m.needsTransfer = mediaNeedsTransfer(m.url);
m.url = toRelativeUrl(m.url);
```

```

2021-08-13 19:48 UTC, beatthat submitted a review, later dismissed

2021-08-13 23:19 UTC, beatthat approved these changes
looks great! once it's tested in integrate env, merge it

2021-08-13 23:20 UTC, merged